name: build dist

on:
  create:
    tags:

jobs:
  linux-build:
    name: build on linux
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: apt update
      run: |
        sudo apt-get update
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: cache NDK
      uses: actions/cache@v2
      env:
        cache-name: cache-ndk
      with:
        path: /usr/local/lib/android/sdk/ndk/21.2.6472646
        key: ndk_r21c_linux
    - name: apt install
      run: |
        echo y | sudo apt-get install doxygen libxml2-dev libgrpc++-dev libgrpc-dev libprotobuf-dev protobuf-compiler protobuf-compiler-grpc graphviz cmake ninja-build
    - name: stupid NDK setup workaround for GitHub Actions
      run: sudo mkdir -p /usr/local/lib/android/sdk/ndk && sudo chmod 777 /usr/local/lib/android/sdk/ndk
    - name: setup gpg necessities
      run: sudo bash -c "echo '$GPG_KEY_CONTENTS' | base64 -d > '$SIGNING_SECRET_KEY_RING_FILE'"
      env:
        GPG_KEY_CONTENTS: ${{ secrets.GPG_KEY_CONTENTS }}
        SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
    - name: rewrite build.gradle to require signing
      run: |
        sed -i "s/signing {}/signing { sign (publishing.publications) }/" java/publish-pom.gradle
    - name: publish
      run: make publish-global
      env:
        USERNAME: atsushieno
        GITHUB_TOKEN: ${{ secrets.MAVEN_PAT }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
        SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
    - name: prepare GitHub Pages
      run: |
        cp -R docs/native/html gh-pages/native
        cp -R java/androidaudioplugin/build/dokka/html gh-pages/kotlin/androidaudioplugin
    - name: deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.2
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      with:
        branch: gh-pages
        folder: gh-pages

  osx-build:
    name: build on osx
    runs-on: macos-10.15
    if: false
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: cache NDK
      uses: actions/cache@v2
      env:
        cache-name: cache-ndk
      with:
        path: /Users/runner/Library/Android/sdk/ndk/21.2.6472646
        key: ndk_r21c_osx
    - name: install deps
      run: |
        brew tap grpc/grpc && brew install doxygen libxml2 ninja graphviz openssl grpc
    - name: workaround for https://github.com/actions/virtual-environments/issues/2228
      run: echo cmake.dir=/usr/local > java/local.properties
    - name: build
      run: make
      env:
        ANDROID_SDK_ROOT: /Users/runner/Library/Android/sdk
